export const keys = {
  getUsers: (payload) => ['users', payload],
  getUser: (id) => ['user', id],
  getitles: 'user-titles',
  getUserOwn: (id) => ['user-own', id],
  user: 'user',
  users: 'users',
  quote: 'quote',
  birthday: 'birthday',
  login: 'login',
  links: (payload) => ['links', payload],
  getLink: (id) => ['link', id],
  getAnnouncementById: (id) => ['announcement', id],
  announcement: 'announcement',
  getAnnouncements: 'announcements',
  ceoMessage: 'ceo',
  announcements: 'announcements',
  adminAnnouncements: 'adminAnnouncements',
  events: (payload) => ['events', payload],
  getEvent: (payload) => ['event', payload],
  blog: 'blog',
  blogs: 'blogs',
  getBlog: (payload) => ['blog', payload],
  getLinkCategory: (id) => ['link-category', id],
  linkCategory: 'category',
  getCategories: 'categories',
  location: 'locations',
  locations: 'locations',
  getLocation: (payload) => ['location', payload],
  departments: 'departments',
  bannerImage: 'banner-image',
  getDepartments: (id) => ['department', id],
  workAnniversary: 'work-anniversary',
  documents: 'documents',
  documentDepartment: 'document-department',
  getDocument: (id) => ['document', id],
  getRingGroup: (id) => ['ring-group', id],
  ringGroups: (payload) => ['/ringGroups', payload],
  jobs: 'jobs',
  applicant: (id) => ['applicant', id],
  getJobs: (payload) => ['jobs', payload],
  getJobById: (id) => ['job', id],
  getJob: (id) => ['job', id],
  polls: (payload) => ['polls', payload],
  getPoll: (id) => ['poll', id],
  profitCenter: 'profitCenter',
  profitCenters: (payload) => ['profit-centers', payload],
  getProfitCenter: (id) => ['profitCenter', id],
  selectedRow: 'selectedRow',
  resources: (payload) => ['resources', payload],
  group: 'group',
  getGroup: (id) => ['group', id],
  getUsersById: (id) => ['groupUsers', id],
  groups: (payload) => ['groups', payload],
  courses: (payload) => ['courses', payload],
  getCourse: (payload) => ['course', payload],
  getProgress: (id) => ['courseProgress', id],
  getTopic: (payload) => ['topic', payload],
  getTopicProgress: (payload) => ['topicProgress', payload],
  getTest: (payload) => ['test', payload],
  getCourseReports: (payload) => ['courseReports', payload],
  getUserReports: (payload) => ['userReports', payload],
  getTestResult: (payload) => ['testResult', payload],
  titles: 'titles',
  getUserProgress: (payload) => ['userProgress', payload],
  getTitle: (id) => ['titles', id],
  getCourseStats: (id) => ['courseStats', id],
};
